version: '3.5'
services:
  erpansfer-api:
    build:
      context: .
      dockerfile: 'Dockerfile'
      target: development
    container_name: erpansfer-api-dev
    ports:
      - '3001:3000'
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - default
    depends_on:
      - postgres

  postgres:
   image: postgres:13
   container_name: postgres
   networks: 
    - default
   env_file:
    - .env
   ports:
    - 5432:5432
   volumes:
    - ./data:/var/lib/postgresql/data
